org: hung34atp
app: organization
service: organization

frameworkVersion: '2'

plugins: # List of plugins of use on application
  - serverless-offline # Get your serverless configuration and run the server local
  - serverless-plugin-typescript-express # Help us with configuration typescript on serverless

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  api:
    handler: src/server.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY
